export type Country = { code: string; name: string; dial: string; flag: string };

// All African countries with dial codes. Niger, Nigeria, Mali, Burkina, Algérie en tête.
export const AFRICAN_COUNTRIES: Country[] = [
  { code: "NE", name: "Niger", dial: "+227", flag: "🇳🇪" },
  { code: "NG", name: "Nigeria", dial: "+234", flag: "🇳🇬" },
  { code: "ML", name: "Mali", dial: "+223", flag: "🇲🇱" },
  { code: "BF", name: "Burkina Faso", dial: "+226", flag: "🇧🇫" },
  { code: "DZ", name: "Algérie", dial: "+213", flag: "🇩🇿" },
  { code: "AO", name: "Angola", dial: "+244", flag: "🇦🇴" },
  { code: "BJ", name: "Bénin", dial: "+229", flag: "🇧🇯" },
  { code: "BW", name: "Botswana", dial: "+267", flag: "🇧🇼" },
  { code: "BI", name: "Burundi", dial: "+257", flag: "🇧🇮" },
  { code: "CM", name: "Cameroun", dial: "+237", flag: "🇨🇲" },
  { code: "CV", name: "Cap-Vert", dial: "+238", flag: "🇨🇻" },
  { code: "CF", name: "Centrafrique", dial: "+236", flag: "🇨🇫" },
  { code: "TD", name: "Tchad", dial: "+235", flag: "🇹🇩" },
  { code: "KM", name: "Comores", dial: "+269", flag: "🇰🇲" },
  { code: "CG", name: "Congo", dial: "+242", flag: "🇨🇬" },
  { code: "CD", name: "RD Congo", dial: "+243", flag: "🇨🇩" },
  { code: "CI", name: "Côte d'Ivoire", dial: "+225", flag: "🇨🇮" },
  { code: "DJ", name: "Djibouti", dial: "+253", flag: "🇩🇯" },
  { code: "EG", name: "Égypte", dial: "+20", flag: "🇪🇬" },
  { code: "GQ", name: "Guinée équatoriale", dial: "+240", flag: "🇬🇶" },
  { code: "ER", name: "Érythrée", dial: "+291", flag: "🇪🇷" },
  { code: "SZ", name: "Eswatini", dial: "+268", flag: "🇸🇿" },
  { code: "ET", name: "Éthiopie", dial: "+251", flag: "🇪🇹" },
  { code: "GA", name: "Gabon", dial: "+241", flag: "🇬🇦" },
  { code: "GM", name: "Gambie", dial: "+220", flag: "🇬🇲" },
  { code: "GH", name: "Ghana", dial: "+233", flag: "🇬🇭" },
  { code: "GN", name: "Guinée", dial: "+224", flag: "🇬🇳" },
  { code: "GW", name: "Guinée-Bissau", dial: "+245", flag: "🇬🇼" },
  { code: "KE", name: "Kenya", dial: "+254", flag: "🇰🇪" },
  { code: "LS", name: "Lesotho", dial: "+266", flag: "🇱🇸" },
  { code: "LR", name: "Libéria", dial: "+231", flag: "🇱🇷" },
  { code: "LY", name: "Libye", dial: "+218", flag: "🇱🇾" },
  { code: "MG", name: "Madagascar", dial: "+261", flag: "🇲🇬" },
  { code: "MW", name: "Malawi", dial: "+265", flag: "🇲🇼" },
  { code: "MR", name: "Mauritanie", dial: "+222", flag: "🇲🇷" },
  { code: "MU", name: "Maurice", dial: "+230", flag: "🇲🇺" },
  { code: "MA", name: "Maroc", dial: "+212", flag: "🇲🇦" },
  { code: "MZ", name: "Mozambique", dial: "+258", flag: "🇲🇿" },
  { code: "NA", name: "Namibie", dial: "+264", flag: "🇳🇦" },
  { code: "RW", name: "Rwanda", dial: "+250", flag: "🇷🇼" },
  { code: "ST", name: "Sao Tomé-et-Principe", dial: "+239", flag: "🇸🇹" },
  { code: "SN", name: "Sénégal", dial: "+221", flag: "🇸🇳" },
  { code: "SC", name: "Seychelles", dial: "+248", flag: "🇸🇨" },
  { code: "SL", name: "Sierra Leone", dial: "+232", flag: "🇸🇱" },
  { code: "SO", name: "Somalie", dial: "+252", flag: "🇸🇴" },
  { code: "ZA", name: "Afrique du Sud", dial: "+27", flag: "🇿🇦" },
  { code: "SS", name: "Soudan du Sud", dial: "+211", flag: "🇸🇸" },
  { code: "SD", name: "Soudan", dial: "+249", flag: "🇸🇩" },
  { code: "TZ", name: "Tanzanie", dial: "+255", flag: "🇹🇿" },
  { code: "TG", name: "Togo", dial: "+228", flag: "🇹🇬" },
  { code: "TN", name: "Tunisie", dial: "+216", flag: "🇹🇳" },
  { code: "UG", name: "Ouganda", dial: "+256", flag: "🇺🇬" },
  { code: "ZM", name: "Zambie", dial: "+260", flag: "🇿🇲" },
  { code: "ZW", name: "Zimbabwe", dial: "+263", flag: "🇿🇼" },
];
