/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSendRouteImport } from './routes/app/send'
import { Route as AppProductsRouteImport } from './routes/app/products'
import { Route as AppOrderRouteImport } from './routes/app/order'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppContactRouteImport } from './routes/app/contact'
import { Route as AppAdminRouteImport } from './routes/app/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSendRoute = AppSendRouteImport.update({
  id: '/app/send',
  path: '/app/send',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/app/products',
  path: '/app/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrderRoute = AppOrderRouteImport.update({
  id: '/app/order',
  path: '/app/order',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/app/notifications',
  path: '/app/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/app/contact',
  path: '/app/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/contact': typeof AppContactRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/order': typeof AppOrderRoute
  '/app/products': typeof AppProductsRoute
  '/app/send': typeof AppSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/contact': typeof AppContactRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/order': typeof AppOrderRoute
  '/app/products': typeof AppProductsRoute
  '/app/send': typeof AppSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/contact': typeof AppContactRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/order': typeof AppOrderRoute
  '/app/products': typeof AppProductsRoute
  '/app/send': typeof AppSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/admin'
    | '/app/contact'
    | '/app/dashboard'
    | '/app/history'
    | '/app/notifications'
    | '/app/order'
    | '/app/products'
    | '/app/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/admin'
    | '/app/contact'
    | '/app/dashboard'
    | '/app/history'
    | '/app/notifications'
    | '/app/order'
    | '/app/products'
    | '/app/send'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/app/admin'
    | '/app/contact'
    | '/app/dashboard'
    | '/app/history'
    | '/app/notifications'
    | '/app/order'
    | '/app/products'
    | '/app/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AppAdminRoute: typeof AppAdminRoute
  AppContactRoute: typeof AppContactRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrderRoute: typeof AppOrderRoute
  AppProductsRoute: typeof AppProductsRoute
  AppSendRoute: typeof AppSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/send': {
      id: '/app/send'
      path: '/app/send'
      fullPath: '/app/send'
      preLoaderRoute: typeof AppSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/products': {
      id: '/app/products'
      path: '/app/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/order': {
      id: '/app/order'
      path: '/app/order'
      fullPath: '/app/order'
      preLoaderRoute: typeof AppOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/app/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/history': {
      id: '/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/contact': {
      id: '/app/contact'
      path: '/app/contact'
      fullPath: '/app/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AppAdminRoute: AppAdminRoute,
  AppContactRoute: AppContactRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrderRoute: AppOrderRoute,
  AppProductsRoute: AppProductsRoute,
  AppSendRoute: AppSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
