/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWifiRouteImport } from './routes/app/wifi'
import { Route as AppSendRouteImport } from './routes/app/send'
import { Route as AppProductsRouteImport } from './routes/app/products'
import { Route as AppOrderRouteImport } from './routes/app/order'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppLivraisonRouteImport } from './routes/app/livraison'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppContactRouteImport } from './routes/app/contact'
import { Route as AppColisRouteImport } from './routes/app/colis'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppAdedetaRouteImport } from './routes/app/adedeta'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWifiRoute = AppWifiRouteImport.update({
  id: '/app/wifi',
  path: '/app/wifi',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSendRoute = AppSendRouteImport.update({
  id: '/app/send',
  path: '/app/send',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/app/products',
  path: '/app/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrderRoute = AppOrderRouteImport.update({
  id: '/app/order',
  path: '/app/order',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/app/notifications',
  path: '/app/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLivraisonRoute = AppLivraisonRouteImport.update({
  id: '/app/livraison',
  path: '/app/livraison',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/app/history',
  path: '/app/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/app/contact',
  path: '/app/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppColisRoute = AppColisRouteImport.update({
  id: '/app/colis',
  path: '/app/colis',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdedetaRoute = AppAdedetaRouteImport.update({
  id: '/app/adedeta',
  path: '/app/adedeta',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/adedeta': typeof AppAdedetaRoute
  '/app/admin': typeof AppAdminRoute
  '/app/colis': typeof AppColisRoute
  '/app/contact': typeof AppContactRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/livraison': typeof AppLivraisonRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/order': typeof AppOrderRoute
  '/app/products': typeof AppProductsRoute
  '/app/send': typeof AppSendRoute
  '/app/wifi': typeof AppWifiRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/adedeta': typeof AppAdedetaRoute
  '/app/admin': typeof AppAdminRoute
  '/app/colis': typeof AppColisRoute
  '/app/contact': typeof AppContactRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/livraison': typeof AppLivraisonRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/order': typeof AppOrderRoute
  '/app/products': typeof AppProductsRoute
  '/app/send': typeof AppSendRoute
  '/app/wifi': typeof AppWifiRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/adedeta': typeof AppAdedetaRoute
  '/app/admin': typeof AppAdminRoute
  '/app/colis': typeof AppColisRoute
  '/app/contact': typeof AppContactRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/history': typeof AppHistoryRoute
  '/app/livraison': typeof AppLivraisonRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/order': typeof AppOrderRoute
  '/app/products': typeof AppProductsRoute
  '/app/send': typeof AppSendRoute
  '/app/wifi': typeof AppWifiRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/adedeta'
    | '/app/admin'
    | '/app/colis'
    | '/app/contact'
    | '/app/dashboard'
    | '/app/history'
    | '/app/livraison'
    | '/app/notifications'
    | '/app/order'
    | '/app/products'
    | '/app/send'
    | '/app/wifi'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/adedeta'
    | '/app/admin'
    | '/app/colis'
    | '/app/contact'
    | '/app/dashboard'
    | '/app/history'
    | '/app/livraison'
    | '/app/notifications'
    | '/app/order'
    | '/app/products'
    | '/app/send'
    | '/app/wifi'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/adedeta'
    | '/app/admin'
    | '/app/colis'
    | '/app/contact'
    | '/app/dashboard'
    | '/app/history'
    | '/app/livraison'
    | '/app/notifications'
    | '/app/order'
    | '/app/products'
    | '/app/send'
    | '/app/wifi'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AppAdedetaRoute: typeof AppAdedetaRoute
  AppAdminRoute: typeof AppAdminRoute
  AppColisRoute: typeof AppColisRoute
  AppContactRoute: typeof AppContactRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLivraisonRoute: typeof AppLivraisonRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrderRoute: typeof AppOrderRoute
  AppProductsRoute: typeof AppProductsRoute
  AppSendRoute: typeof AppSendRoute
  AppWifiRoute: typeof AppWifiRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wifi': {
      id: '/app/wifi'
      path: '/app/wifi'
      fullPath: '/app/wifi'
      preLoaderRoute: typeof AppWifiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/send': {
      id: '/app/send'
      path: '/app/send'
      fullPath: '/app/send'
      preLoaderRoute: typeof AppSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/products': {
      id: '/app/products'
      path: '/app/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/order': {
      id: '/app/order'
      path: '/app/order'
      fullPath: '/app/order'
      preLoaderRoute: typeof AppOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/app/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/livraison': {
      id: '/app/livraison'
      path: '/app/livraison'
      fullPath: '/app/livraison'
      preLoaderRoute: typeof AppLivraisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/history': {
      id: '/app/history'
      path: '/app/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/contact': {
      id: '/app/contact'
      path: '/app/contact'
      fullPath: '/app/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/colis': {
      id: '/app/colis'
      path: '/app/colis'
      fullPath: '/app/colis'
      preLoaderRoute: typeof AppColisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/adedeta': {
      id: '/app/adedeta'
      path: '/app/adedeta'
      fullPath: '/app/adedeta'
      preLoaderRoute: typeof AppAdedetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AppAdedetaRoute: AppAdedetaRoute,
  AppAdminRoute: AppAdminRoute,
  AppColisRoute: AppColisRoute,
  AppContactRoute: AppContactRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLivraisonRoute: AppLivraisonRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrderRoute: AppOrderRoute,
  AppProductsRoute: AppProductsRoute,
  AppSendRoute: AppSendRoute,
  AppWifiRoute: AppWifiRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
